create database bancoDados;
use bancoDados;

create table receita (
id_receita int auto_increment Primary key,  
nome_receita varchar(45),    
modopreparo varchar (2000),
compatibilidade int,
cont_ingred int
);
create table ingrediente (
	id_ingrediente int auto_increment Primary key,
	nome_ingrediente varchar(45) 
       
   
);
UPDATE receita  SET   compatibilidade=compatibilidade+1 WHERE (nome_receita='abc');
 SELECT nome_receita  FROM receita r where r.compatibilidade>0 order by r.compatibilidade desc;
create table composicao (
	cod_receita int ,
	cod_ingrediente int ,
	quant varchar (45),
	Primary key (cod_receita,cod_ingrediente),
        foreign key (cod_receita) references receita(id_receita),
	foreign key (cod_ingrediente) references ingrediente (id_ingrediente)
    
);

insert into Ingrediente values(1,'manteiga');
insert into Ingrediente values(2,'açucar');
insert into Ingrediente values(3,'ovos');
insert into Ingrediente values(4,'essência baunilha');
insert into Ingrediente values(5,'bicarbonato de sódio');
insert into Ingrediente values(6,'Nutella');
insert into Ingrediente values(7,'farinha de trigo');
insert into Ingrediente values(8,'frango');
insert into Ingrediente values(9,'oregano');
insert into Ingrediente values(10,'tomate');
insert into Ingrediente values(11,'presunto');
insert into Ingrediente values(12,'mussarela');
insert into Ingrediente values(13,'leite');
insert into Ingrediente values(14,'farinha de rosca');
insert into Ingrediente values(15,'carne moída');
insert into Ingrediente values(16,'cebola');
insert into Ingrediente values(17,'alho');
insert into Ingrediente values(18,'pimenta');
insert into Ingrediente values(19,'aipo');
insert into Ingrediente values(20,'sal');
insert into Ingrediente values(21,'azeite');
insert into Ingrediente values(22,'mangericão');
insert into Ingrediente values(23,'cogumelo');
insert into Ingrediente values(24,'espaguete');
insert into Ingrediente values(25,'queijo parmesão');
insert into Ingrediente values(26,'limão');
insert into Ingrediente values(27,'atum');
insert into Ingrediente values(28,'molho de tomate');
insert into Ingrediente values(29,'arroz');
insert into Ingrediente values(30,'caldo knor');
insert into Ingrediente values(31,'abacate');
insert into Ingrediente values(32,'camarão');
insert into Ingrediente values(33,'lima');
insert into Ingrediente values(34,'gengibre');
insert into Ingrediente values(35,'coentro');
insert into Ingrediente values(36,'ervilhas');
insert into Ingrediente values(37,'salsisha');
insert into Ingrediente values(38,'bacon');
insert into Ingrediente values(39,'linguiça');
insert into Ingrediente values(40,'pão');
insert into Ingrediente values(41,'cenoura');
insert into Ingrediente values(42,'pão integral');
insert into Ingrediente values(43,'cereja');
insert into Ingrediente values(44,'oleo vegetal');
insert into Ingrediente values(45,'cerveja');
insert into Ingrediente values(46,'canela');
insert into Ingrediente values(47,'cravo da índia');
insert into Ingrediente values(48,'maionese');
insert into Ingrediente values(49,'azeitona');
insert into Ingrediente values(50,'mostarda');
insert into Ingrediente values(51,'extrato de baunilha');
insert into Ingrediente values(52,'salva');
insert into Ingrediente values(53,'queijo provolone');
insert into Ingrediente values(54,'molho ingles');
insert into Ingrediente values(55,'semente de papoula');
insert into Ingrediente values(56,'vinagre');
insert into Ingrediente values(57,'cebolinha');
insert into Ingrediente values(58,'pickles');
insert into Ingrediente values(59,'alface');
insert into Ingrediente values(60,'manjericão');
insert into Ingrediente values(61,'molho de sojasoja');
insert into Ingrediente values(62,'vinagre de arroz');
insert into Ingrediente values(63,'chocolate');
insert into Ingrediente values(64,'sorvete de creme');
insert into Ingrediente values(65,'doce de leite');
insert into Ingrediente values(66,'biscoito champanhe');
insert into Ingrediente values(67,'fermento em pó');
insert into Ingrediente values(68,'doce de goiaba');
insert into Ingrediente values(69,'creme de leite');
insert into Ingrediente values(70,'beterraba');
insert into Ingrediente values(71,'laranja');
insert into Ingrediente values(72,'açucar mascavo');
insert into Ingrediente values(73,'batata doce');
insert into Ingrediente values(74,'maçã');
insert into Ingrediente values(75,'abóbora');
insert into Ingrediente values(76,'avelã');
insert into Ingrediente values(77,'vinho branco');
insert into Ingrediente values(78,'caldo de legumes');
insert into Ingrediente values(79,'rúcula');
insert into Ingrediente values(80,'gelatina');
insert into Ingrediente values(81,'queijo creme');
insert into Ingrediente values(82,'leite condensado');
insert into Ingrediente values(83,'iorgute');
insert into Ingrediente values(84,'farinha de milho');
insert into Ingrediente values(85,'carne de boi');
insert into Ingrediente values(86,'nata');
insert into Ingrediente values(87,'tangerina');
insert into Ingrediente values(88,'farinha de aveia');
insert into Ingrediente values(89,'farinha de amêndoa');
insert into Ingrediente values(90,'mel');
insert into Ingrediente values(91,'banana');
insert into Ingrediente values(92,'nozes');
insert into Ingrediente values(93,'carne de peru');
insert into Ingrediente values(94,'pimentão');
insert into Ingrediente values(95,'gergelim');
insert into Ingrediente values(96,'óleo de gergelim');
insert into Ingrediente values(97,'amendoim');
insert into Ingrediente values(98,'framboesa');
insert into Ingrediente values(99,'frutos vermelhos');
insert into Ingrediente values(100,'chocolate branco');
insert into Ingrediente values(101,'champanhe');
insert into Ingrediente values(102,'leite de coco');
insert into Ingrediente values(103,'morango');
insert into Ingrediente values(104,'mascarpone');
insert into Ingrediente values(105,'abacaxi em calda');
insert into Ingrediente values(106,'farinha de castanha');
insert into Ingrediente values(107,'coco');
insert into Ingrediente values(108,'cacau');
insert into Ingrediente values(109,'alecrim');
insert into Ingrediente values(110,'costelinha');
insert into Ingrediente values(111,'cominho');
insert into Ingrediente values(112,'folha de louro');
insert into Ingrediente values(113,'batata');
insert into Ingrediente values(114,'maizena');
insert into Ingrediente values(115,'feijão');
insert into Ingrediente values(116,'bacon');
insert into Ingrediente values(117,'salsisha italiana');
insert into Ingrediente values(118,'biscoito recheado chocolate');
insert into Ingrediente values(119,'leite em pó');
insert into Ingrediente values(120,'romã');
insert into Ingrediente values(121,'salsinha');

insert into Receita(id_receita,nome_receita,modopreparo ) values (1,'Cookies recheados com Nutella','Com a batedeira bata a manteiga e o açúcar até formar uma massa homogênea. Adicione os ovos e a essência de baunilha, bata bem até incorporar. Em outro recipiente coloque a farinha e o bicarbonato de sódio, misture. Adicione metade dessa mistura seca à outra mistura, misture delicadamente, adicione a outra metade e misture delicadamente até incorporar. Adicione as gotas de chocolate e misture. Pega uma colher (de sopa) de massa, faça uma bolinha, depois amasse, coloque 1 colher de chá de nutella no meio, e faça novamente uma bola, cobrindo a nutella. Faça isso com toda a massa. Unte uma forma grande e cubra uma forma com papel manteiga. Coloque as bolinhas, deixando uma espaço entre elas, um espaço de 2 dedos mais ou menos, porque eles iram espalhar na forma quando assarem. Asse no forno pré-aquecido à 180ºC de 12-14 minutos. Retire do forno, deixe esfriar um pouco e sirva.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (2,'Frango recheado com queijo e presunto','Abra as sobrecoxas e amasse-as com um martelo de carne. Se não tiver, você pode usar um rolo ou algum pote pesado. Pré-aqueça o forno a 160º. Adicione sal e pimenta às sobrecoxas. Polvilhe um pouco de orégano seco ou fresco picado. Adicionar 5 ou 6 tiras de tomate seco. Adicionar uma fatia de presunto, parta em pedaços para caber. Adicionar uma fatia de queijo muçarela em cima do presunto. Enrole o frango para que o queijo e o presunto fiquem por dentro. Faça uma mistura de ovo e leite. Bata até obter uma mistura homogênea. Coloque farinha de trigo em um prato, e farinha de rosca em outra prato. Passe cada pedaço de frango na farinha de trigo, depois no ovo, e depois na farinha de rosca. Em uma panela, adicione um pouco de azeite de oliva e frite o frango até dourar ambos os lados. Coloque no forno pré-aquecido e asse por 20 minutos a 160º. No final pode servir.');
insert into Receita(id_receita,nome_receita,modopreparo )  values (3,'Massa bolonhesa especial', 'Corte os tomates e a cebola em pedaços e corte o pimento e os dentes de alho em bocadinhos. Insira no liquidificador para ficar com um molho espesso. Numa frigideira com azeite pré-aquecido, colocque o molho. Envolva a carne e tempere-a com sal. Quando estiver quase cozida, deite o mangericão e deixe cozinhar por mais uns minutos. À parte, numa frigideira com azeite, salteie os cogumelos cortados. Quando estiverem dourados coloque a salsa picadinha e deixe cozinhar mais uns minutos para dar sabor. Em seguida misture-a ao molho de carne, misturando bem e retirando do fogo. Cosa al dente o esparguete em agua abundante com sal e um pouco de azeite para não pegar, por volta de 7 minutos. Sirva o esparguete com o molho de carne por cima e, se desejar, polvilhe com queijo parmesão (opcional).');
insert into Receita (id_receita,nome_receita,modopreparo ) values (4,'Peito de frango no microondas','Comece por temperar os bifes com o sumo do limão, adicionando também o sal e a salsa. Em seguida, ponha-os numa travessa que possa ir ao microondas e cubra-os com as rodelas de tomate e cebola. Leve ao microondas na potência máxima durante 8 minutos e sirva em seguida.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (5,'Arroz de atum ','Numa panela faça o refugado para o Arroz com óleo ou azeite, 1/2 caldo knorr e junte cebola picada qb. Adicionar o arroz (1,5 caneca) e mexa bem, assim que o arroz estiver misturado com o refugado adicione a água (3 canecas) e deixe cozer. Noutra panela, faça o refugado para o Atum com óleo ou azeite, 1/2 caldo knorr, cebola picada qb e molho de tomate a gosto. Quando o refugado estiver pronto junte as 3 latas de atum e o óleo de uma das latas. Deixar cozinhar aproximadamente 10 minutos, vá mexendo. Numa forma para bolos, faça 3 camadas: 2 de arroz e uma de atum: 1º uma de arroz, depois uma de atum e de seguida cobra com a 3ª camada de arroz. De seguida, desenforme e acompanhar com uma salada de alface e tomate.',);
insert into Receita (id_receita,nome_receita,modopreparo ) values (6,'Arroz com camarão e abacate','Comece por temperar o miolo de camarão com o sumo e a raspa da lima, o dente de alho ralado, bem como o gengibre. Acrescente o sal e a pimenta e deixe marinar um pouco. Entretanto descasque o abacate e corte-o em fatias finas. Leve uma frigideira anti aderente ao lume com o azeite e deixe aquecer bem. Junte o camarão, escorrido da marinada e deixe saltear até ficar cozinhado. Junte depois a marinhada, deixe fervilhar um pouco e retire do lume. No fundo de uma taça coloque o arroz previamente aquecido e cubra com o abacate em fatias. Por cima disponha o camarão e regue o arroz com o molho que se formou. Polvilhe tudo com os coentros frescos e sirva de imediato.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (7,'Risoto de salchicha e queijo','Cozinhe numa panela a cebola e o dente de alho descascado e picado com o azeite. Quando a cebola ficar translúcida adicionar o arroz e o pimento já limpo e cortado aos cubinhos. Deixe refogar enquanto vai mexendo. Regue com o caldo de carne e junte o tomate limpo e ralado. Misture e baixe o lume quando levantar fervura. Juntar a chouriça e o bacon. Cozinhe até o arroz ficar cozido (adicionar água se for preciso).Juntar as ervilhas e as salsichas. Rectificar o tempero. Deixe cozer mais uns 3 a 4 minutos e retire para um terrina de vidro. Polvilhe com bastante queijo ralado e leve ao forno.Retire quando o queijo estiver na totalidade derretido.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (8,'Pão de alho','Corte o pão às fatias e pique os dentes de alho em pedacinhos pequeninos (ou se preferir, esmague-os). Leve-os ao lume com o azeite para alourarem um pouco e, em seguida, junte a salsa picada. Depois barre o pão com o "molho" de azeite e alho e envolva-o dentro de folhas de alumínio. Leve ao forno (a 220ºC) durante 15 minutos. Quem adorar alho pode acrescentar mais dentes de alho. Sirva como entrada ou acompanhamento.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (9,'Omelete vegetariana','Num prato fundo quebre os ovos e use um bata-os até espumar. Acrescente uma pitada de sal e pimenta, a cenoura, cebola, tomate e mussarela e envolva os ingredientes. Aqueça uma frigideira anti-aderente com óleo suficiente para forrar todo o fundo. Depois de estar quente, despeje gentilmente a sua omelete na frigideira e deixe fritar até que a parte de baixo esteja firme. Vire a omelete para cozinhar todo o ovo e os demais ingredientes. Numa torradeira torre o pão integral. Monte o seu prato com as 2 torradas, a salada de folhas regada com um pouco de azeite e a omelete');
insert into Receita (id_receita,nome_receita,modopreparo ) values (10,'Aros de cebola fritos','Num recipiente misture a farinha com a cerveja, tempere com o sal e a pimenta e deixa-se repousar durante 30 minutos. Quebre o ovo e separe a gema da clara. Bata a clara em castelo e junte a gema ao preparado anterior (com a farinha e cerveja). Descasque as cebolas corte às rodelas não muito grossas, passe pelo preparado e frite em óleo bem quente. Depois de fritas escorra em papel absorvente e sirva com molhos a gosto.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (11,'Compota de tomate','Pele o tomate, retire as grainhas e deixe escorrer por 6 horas. Num tacho, misture o açúcar com o tomate. Junte a canela, a casca de limão e os cravinhos. Leve a ferver até fazer ponto de estrada. Guarde em frascos escaldados e secos e feche-os. Encha os frascos até à borda. Limpe a borda deixando-a bem seca. Feche com a tampa, enroscando bem e virando com a tampa para baixo até arrefecer. O processos deve ser efetuado com o doce acabado de fazer, ou seja, na temperatura bem quente.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (12,'Tomates Recheados','Retira-se o miolo do tomate, depois de se lhe tirar uma rodela para servir de tampa. Depois faz-se uma mistura com os ingredientes mais o que se retirou do interior do tomate. Após a junção dos ingredientes recheiam-se os tomates e coloca-se a rodela a servir de tampa. Vão ao frigorífico durante 1 hora.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (13,'Ovos recheados','Coza  os ovos e deixe  esfriar completamente. Corte-os de forma oval. Retire as gemas cozidas, pique-as com salsa, manteiga, leite, sal e a pimenta. Misture todos os ingredientes e encha as cavidades dos ovos. Estão prontos a servir. Para  melhor guarnecer a travessa, disponha os ovos com ervilhas, cenouras cozidas, partidas aos palitos e salsa picada finamente.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (14,'Sanduíche havaiana de queijo e presunto','Comece por pré-aquecer o forno a 220ºC. Unte uma assadeira com margarina. Forre o fundo da panela com as metades inferiores dos pequenos pães doces havaianos. Cubra os pães com fatias finas de presunto. Em seguida coloque uma fatia de queijo provolone. Adicione cream cheese (ou maionese), e cubra com a parte superior do pãozinho. Misture todos os ingredientes da cobertura e coloque sobre o pãozinho. Cubra com papel alumínio e asse no forno pré-aquecido por aproximadamente 15 minutos, ou até que o queijo esteja derretido. Sirva quente!');
insert into Receita (id_receita,nome_receita,modopreparo ) values (15,'Ovos benedict','Coloque 1 litro de agua a ferver e tempere com sal e adicione o vinagre. Parta os ovos numa conxa levemente pincelada com um pouco de óleo e deslize a conxa para a panela com a agua. Deixe cozinhar os ovos por aproximadamente 5 minutos em lume baixo. Dobre levemente 2 vezes as fatias de fiambre e frite o fiambre numa colher de sopa de manteiga quente, coloque o fiambre frito sobre cada fatia de pão. Para o molho: Aqueca 1/8 l de agua, misture o conteúdo do saco de molho hollandais, bata com o batedor manual até ferver. Corte 125g de manteiga em pedaços pequenos e adicione ao molho hollandais mantendo o lume baixo. Espalhe um pouco de molho hollandais sobre cada fatia de pão com fiambre e ponha 1 ovo escalfado por cima do molho. Lave as cebolinhas e corte em rolinhos pequenos, e em seguida polvilhe-as nos ovos. Decore com a salsa.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (16,'Paté de atum','Desfaça o atum em pedaços e esprema bem para retirar toda a gordura e ponha de lado. Num recipiente junte a maionese, o ketchup e o molho inglês até ficar uniforme. Em seguida junte o atum ao molho e leve ao frigorífico. É excelente para barrar no pão ou para baguettes');
insert into Receita (id_receita,nome_receita,modopreparo ) values (17,'Sanduíche de frango','Coza os peitos de frango e, depois de cozido, pique-o. Pique também os talos de aipo, a cebola e os pickles. Misture muito bem o frango com salsa, maionese, pickles, cebola e o aipo. Tempere com alho em pó, e junte sal e pimenta. Sirva com fatias de pão (se quiser pode tostar o pão) e faça um acompanhamento com folhas de alface.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (18,'Sanduíche de abacate, alface e tomate','Para cada sanduíche, torre duas fatias de pão integral. Enquanto o pão torra, corte o seu tomate e abacate. Deite a maionese maionese, conforme goste, em um dos lados de cada fatia de pão torrado. Adicione uma camada de fatias de abacate e polvilhe com um pouco de sal kosher. Adicione uma camada de alface e uma camada de rodelas de tomate. Polvilhe também os tomates com um pouco de sal. Cubra com a segunda fatia de pão torrado. Corte o sanduíche ao meio, se quiser, para torná-la mais fácil de comer.');
insert into Receita (id_receita,nome_receita,modopreparo )  values (19,'Salada de tomate com molho de soja','Certifique-se o molho de soja que você está usando realmente é feito de soja. Muito do que é rotula como o molho de soja é apenas água com sabor e não o molho de soja, que é feito de soja fermentada. Verifique o rótulo para se certificar de que você está comprando a soja real! Não há medições nesta receita. Basta borrifar os ingredientes sobre os tomates cortados e ajuste ao seu gosto. Corte os tomates em fatias e arrume-os num prato de servir. Levemente regue o azeite sobre os tomates.  Polvilhe com vinagre de arroz temperado. Polvilhe bem com molho de soja. Polvilhe com sal. Atire algumas folhas de manjericão em fatias finas sobre os tomates. Sirva à temperatura ambiente.');
insert into Receita (id_receita,nome_receita,modopreparo )  values (20,'Mousse de chocolate com 1 ingrediente','Comece por picar o chocolate e coloque-o num recipiente. Ferva 3/4 de xícara de água e derrame no chocolate, mexa com uma colher até derreter todo o chocolate. Em seguida, com a batedeira bata até esfriar por completo e leve ao congelador durante 1 hora. Por fim sirva e delicie-se com esta excelente sobremesa.');
insert into Receita (id_receita,nome_receita,modopreparo )  values (21,'Pavê de doce de leite com sorvete','Vá alternando para dentro de uma taça o doce de leite, os biscoitos quebradinhos e o sorvete, até chegar ao topo. Decore com doce de leite e biscoitos. Você também pode montar em grande quantidade dentro de uma forma e colocar no congelador até chegar a hora de servir. Depois é só aproveitar.');
insert into Receita(id_receita,nome_receita,modopreparo )  values (22,'Rocambole baiano','Bata as claras em neve em uma batedeira, acrescentando o açúcar. Junte as gemas e a farinha de trigo. Continue batendo e adicione o fermento. Bata bem a massa e em seguida coloque em uma assadeira grande, de 40cm por 28cm, untada com manteiga e farinha detrigo. Coloque no forno preaquecido à 200°C e deixe assar até que as bordas soltem da assadeira (aproximadamente 15 minutos). Pique as goiabas em pedacinhos. A massa pronta pode ser desenformada com o auxílio de um pano de prato úmido. Coloque o doce de goiaba por cima da massa e em seguida o creme de leite. Enrole a massa com o auxílio de um pano de prato, formando um rocambole. Se desejar, polvilhe com açúcar cristal antes de servir.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (23,'Bolo de Nutella','Bata os ovos numa batedeira até terem triplicado de volume e estarem fofos, o que demora cerca de 5 a 6 minutos. Acrescente depois a nutella previamente aquecida no microondas, numa taça de vidro, durante 20 segundos, para que seja mais simples de envolver no preparado dos ovos. Envolva depois a nutella cuidadosamente, para que os ovos não percam muito volume e coloque a mistura numa forma redonda sem buraco, com cerca de 20cm de diâmetro e previamente forrada e untada com papel vegetal. Leve depois ao forno - 170ºC - durante cerca de 20 a 25 minutos. Deixe arrefecer um pouco e desenforme para o parto de servir. Decore, se gostar com avelãs torradas e açúcar em pó.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (24,'Bolo de Nutella com 2 ingredientes','Comece por pré-aaquecer o forno a 180ºC. Coloque papel manteiga numa assadeira redonda de aproximadamente 20 cm. Coloque os ovos na batedeira e bata em velocidade alta por 6 minutos, até que o volume triplique. Irá espumar e crescer bastante. Coloque a Nutella em um vasilhame médio e leve ao microondas por 15 – 20 segundos em potência média/alta, para ele ficar mais molinho, como chocolate derretido. Vá adicionando a nutella ao ovo batido aos poucos.  Você pode fazer essa etapa em 3 passos: Coloque um pouco de nutella e vá misturando até estar completamente misturado, depois adicione mais nutella e misture novamente... até colocar toda a nutella na mistura. Coloque a mistura na assadeira e cozinhe por 25-30 minutos ou até estiver completamente assado (espete o centro do bolo com um palito de dentes e se ele sair limpo, está pronto!!!) Deixe o bolo esfriar na assadeira! Assim fica mais fácil retirá-lo da forma!');
insert into Receita (id_receita,nome_receita,modopreparo ) values (25,'Bolo mármore de chocolate e beterraba','Bata as 4 gemas com o açúcar e junte a manteiga à temperatura ambiente e bata até obter um creme fofo. Seguidamente misture a farinha peneirada com o fermento e por fim as claras em castelo. Divida depois a massa em 2 partes iguais: numa misture o puré de beterraba, e na outra misture o de chocolate em pó. Unte e polvilhe com farinha uma forma tipo bolo inglês e deite os 2 preparados em camadas alternadas. Leve a cozer em forno médio durante 30, 35 minutos. Depois de cozido deixe arrefecer e desenforme.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (26,'Copinhos de chocolate com ovos moles','Comece por levar a água e o açúcar ao lume e deixe ferver durante 3 minutos, mexendo de vez em quando. Em seguida retire do lume e deixe arrefecer um pouco. Entretanto bata as gemas numa taça e, assim que a calda de açúcar tiver mais fria, junte-a em fio às gemas, misturando bem. Coloque novamente tudo no tacho e leve novamente ao lume, desta vez em lume muito brando, até as gemas começarem a cozinhar e ficar com um creme grosso e rico. Retire do lume e coloque num prato. deixe arrefecer completamente. Encha depois cuidadosamente os copos de chocolate com o doce de ovos. Antes de servir polvilhe-os com um pouco de canela em pó. Sirva como um aperitivo de sobremesa ou a acompanhar o café.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (27,'Cascas de laranja cristalizadas','Corte as cascas de laranjas em tiras finas, com cerca de 4 a 5mm, e coloque-as num tacho com água. Leve o tacho ao lume e deixe levantar fervura. Retire de imediato o tacho do lume, escorra as cascas e repita o processo mais duas vezes. Isto serve para retirar o amargo das cascas (principalmente da parte branca). Escorra finalmente as cascas e coloque-as sobre papel de cozinha para lhes retirar o máximo de humidade. Pese depois as cascas reservadas. Num tacho junte o peso das cascas em açúcar e junte um pouco de água - não é preciso muita quantidade, apenas para molhar o açúcar e ajudar a formar uma calda. Leve o tacho com o açúcar ao lume e deixe começar a ferver, até o açúcar estar dissolvido mas ser uma calda grossa, cerca de 2 ou 3 minutos. Junte depois as cascas de laranja e, sem parar de mexer, deixe cozinhar no açúcar até toda a humidade ter evaporado, e quase não existir calda no tacho - atenção para não deixar agarrar. Coloque depois as cascas de laranja sobre um tabuleiro forrado com papel vegetal, e de imediato comece a juntar açúcar sobre as cascas e a separa-las cuidadosamente com as mãos, de modo a que não se colem. Assim que as cascas deixarem de colar umas às outras e estejam bem separadas, deixe-as ficar a secar, um ou dois dias, ao ar. Depois, guarde-as em frascos hermético. Use-as como mais gostar, em massas de bolos e bolachas, para decorar, ou até para servir como guloseima. Se quiser poderá ainda cobrir uma parte da casca cristalizada com chocolate negro derretido.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (28,'Copinho de cookie','Pré-aqueça o forno a 180 graus, unte os moldes dos copinhos. Numa tigela grande, bata a manteiga, o açúcar mascavo e o granulado. Adicione a gema de ovo e a baunilha e misture até que esteja completamente incorporado. Aos poucos, adicione a farinha e o sal e misture até formar uma massa uniforme. Adicione as mini gotas de chocolate e misture. A massa deve ficar um pouco quebradiça neste ponto. Para formar os copinhos de cookie, coloque a massa nos moldes com uma espessura um pouco grossinha e leve à geladeira por 20/30 minutos. Este procedimento deve ser feito antes dos copinhos irem ao forno. Depois deste tempo, asse os cookies por mais ou menos 20 minutos ou até a massa ficar douradinha. Retire do forno, deixe esfriar completamente, sirva a bebida de sua preferência, deguste o copinho de cookie.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (29,'Snack de batata doce frita','Lave bem as batatas com a pele com a ajuda de uma escova. Limpe toda a sujidade nas cavidades e, com uma faca, retire todas os pedaços que pareçam estragados. Lamine finamente as batatas. Passe bem por água até que a água fique com aspeto límpido. Guarde as batatas com a água no frigorífico durante uma hora. Em seguida seque bem com um pano, antes de fritar. Aqueça bem o óleo, e depois de estar bem quente coloque uma batata de cada vez, para que não se colem umas às outras e fiquem moles. Frite poucas de cada vez. Tire-as do óleo e coloque-as em papel absorvente. Por fim, salpique com sal fino e sirva como acompanhamento.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (30,'Compota de maçã','Coloque todos os ingredientes numa panela grande. Cubra e deixe até ferver. Em seguida, baixe o fogo e cozinhe por 20-30 minutos. Retire do fogo. Remova os paus de canela e a casca de limão. Amasse com o espremedor de batatas. Pronto para servir, quente ou refrigerada. Deliciosa com sorvete de baunilha. Congela facilmente e dura até um ano num freezer frio.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (31,'Compota de abóbora com gengibre cristalizado, laranja e avelãs','Comece por cortar a abóbora em cubos e coloque-a numa panela grande. Junte o açúcar, o gengibre cristalizado bem picadinho e a raspa do vidrado de duas laranjas. Envolva bem, e leve ao lume. Assim que levantar fervura reduza o lume para o mínimo e deixe cozinhar, até que a abóbora esteja macia. Com a varinha mágica triture o doce. Junte as avelãs e deixe ferver novamente até que o doce tenha atingido o ponto, (que deverá testar colocando um pouco de doce num pires e passando com um dedo. Se abrir uma pequena “estrada” que não se une de imediato o doce está no ponto. Tem de ter uma consistência pastosa e não líquida. Coloque a compota ainda quente em frascos de vidro previamente esterilizados e feche-os. Coloque-os depois, virados de “cabeça para baixo” cerca de 30 minutos, de modo a que criem um vácuo natural. Rotule  as compotas e guarde num local seco até consumir. A compota fica sempre deliciosa com requeijão, com panquecas ou simples torradas no pequeno almoço.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (32,'Risoto de abóbora com rúcula','Pique finamente a cebola e leve-a num tacho ao lume juntamente com o azeite. Deixe a cebola começar a ficar translúcida e junte depois o arroz envolvendo bem no refogado. Acrescente o vinho branco e, mexendo sempre deixe o vinho cozinhar até evaporar e ter sido absorvido pelo arroz. Vá depois juntando, aos poucos e poucos e mexendo sempre, o caldo de legumes quente. Quando o arroz tiver absorvido o líquido é que deve misturar mais. Quando o arroz estiver quase cozinhado, acrescente a polpa de abóbora envolvendo bem. Retifique de sal e pimenta e, se necessário acrescente mais caldo de legumes até o arroz estar cozinhado (tem de estar cozinhado mais ainda firme e com um pouco de textura). Quando o arroz estiver pronto, acrescente o parmesão ralado na hora, a rúcula e uma colher de sopa de manteiga. Envolva bem, deixe repousar um ou dois minutos e sirva de imediato com um pouco mais de parmesão.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (33,'Gelatina de chocolate','Coloque a gelatina na meia xícara de água. Coloque o leite numa panela e adicione o leite condensado, aqueça em fogo médio/baixo até que comece a ferver. Seguidamente acrescente a essência de baunilha. Em seguida, na liquidificadora liquefaça o creme de queijo com o leite evaporado, o chocolate de leite e o creme de avelã. Agora vamos derreter o chocolate no microondas e imediatamente adicione o chocolate à mistura no liquidificador, para liquidificar. Em seguida adicione a mistura resultante à panela. Derretemos a gelatina no microondas e adicionamos ao anterior. Vazamos a mistura para um molde de gelatina e levamos à geladeira até ficar firme. Decore de acordo com o seu gosto e sirva.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (34,'Bolo de limão, farinha de milho e iogurte','Bata a manteiga com o açúcar, a raspa do vidrado de dois limões e os ovos inteiros. Misture bem até obter uma mistura homogénea. Acrescente depois o iogurte e o leite, misture e finalmente junte as farinhas e o fermento. Misture tudo bem até obter uma massa homogénea. Coloque a massa numa forma tipo bolo inglês, previamente untada e forrada com papel vegetal, e leve ao forno previamente aquecido a 180ºC durante cerca de 45 minutos ou até o bolo estar cozido. Entretanto prepare a calda. Aproveite o sumo dos limões que usou previamente, até ter cerca de 80ml. Numa panela coloque o sumo de limão e o açúcar e leve a lume brando apenas para aquecer o sumo de derreter o açúcar. Não deixe ferver ou ficará com uma calda demasiado espessa que não penetrará bem no bolo. Assim que o bolo esteja pronto, e sem desenformar, pique-o em toda a superfície com um espeto ou um palito e verta cuidadosamente a calda sobre o bolo. Deixe o bolo absorver toda a calda e arrefecer e só depois o deverá desenformar. Sirva simples ou com chá e um pouco de lemon curd e framboesas frescas.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (35,'Doce de leite macio','Coloque em uma panela grossa o leite condensado, o açúcar e o leite. Leve ao fogo, mexendo sempre, até cozinhar bem, ficar cremoso, engrossar e desgrudar do fundo da panela. Retire a panela do fogo. Mexa rapidamente com uma colher até perder o brilho. Unte uma bancada ou assadeira com manteiga. Despeje o doce sobre a manteiga e ajeite até formar um quadrado. Corte com a faca no formato desejado. O doce ainda estará morno. Deixe esfriar e sirva.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (36,'Stroganoff de boi com cogumelos e massa','Leve a massa a cozer em água temperada de sal até ficar al dente. Entretanto corte o bife em tiras finas e compridas, lamine os dentes de alho e os cogumelos. Reserve. Leve uma frigideira ao lume com um pouco de azeite e deixe aquecer bem. Junte depois as tiras de bife e deixe saltear bem. Junte depois os dentes de alho e tempere com sal e pimenta. Deixe cozinhar uns minutos em lume alto e forte e retire, reservando. Coloque um pouco mais de azeite na frigideira e deixe voltar a aquecer. Junte depois os cogumelos laminados, tempere de sal e pimenta e deixe cozinhar. Quando os cogumelos estiverem murchos junte a carne previamente cozinhada e envolva bem. Junte depois as natas, mexa bem e deixe levantar fervura. Retifique de sal e pimenta. Sirva a carne sobre o esparguete ou fetuccini previamente escorrido.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (37,'Tangerinas em calda da Maria','Lave bem as tangerinas e pique-as com um garfo - várias picadelas em toda a volta. Coloque-as depois a demolhar, em água fria durante 3 dias mudando a água 2 ou 3 vezes por dia. Ao fim deste tempo escorra-as e coza-as em água limpa, até a casca amolecer um pouco (não muito, pois as tangerinas devem manter-se inteiras e não deformadas). Volte a escorrê-las e coloque-as numa taça. Reserve. Num tacho, coloque o açúcar e a água (1 litro de água e 1 kg de açúcar) e leve ao lume. Assim que levantar fervura, conte 2 minutos e desligue. Verta depois esta calda quente sobre as tangerinas e polvilhe com açúcar simples. Reserve. No dia seguinte, (e todos os dias seguintes até atingirem o ponto certo) deve escorrer as tangerinas, ferver a calda de açúcar e colocá-la novamente sobre as tangerinas que são outra vez polvilhadas com açúcar. De  3 em 3 dias, em vês de ferver apenas a calda, ferve também as tangerinas juntamente com a calda(ou seja, nestes dias, as tangerinas não são escorridas). Quando a calda de açúcar ficar bem consistente como o mel, as tangerinas estão prontas.(Quando fiz a receita, fiz com as quantidades indicadas, e todo o processo, desde as tangerinas ficarem de molho, até à calda atingir o ponto desejado, demorou cerca de duas semanas). Depois de prontas guarde as tangerinas em frascos esterilizados. Se notar que elas estão a ganhar espuma ferva outra vez imediatamente. As tangerinas são otimas para decorar bolos e tartes e para servir como se fossem ameixas de elvas, com pão de ló molhadinho ou bolo de chocolate.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (38,'Panquecas de aveia e amêndoa','Numa taça misture a farinha de aveia, com a farinha e amêndoa, o leite, o ovo, o iogurte e o fermento. Misture bem até ficar com uma mistura sem grumos e grossa. Leve um frigideira pequeno ao lume - eu usei daquelas pequeninas de estrelar ovos - e unte-a com um pouco de azeite. Quando estiver quente, coloque um pouco da massa e deixe cozinhar até que se comecem a formar bolinhas à superfície. Vire então a panqueca e dixe cozinhar do outro lado até que fique dourada. Retire para um prato e repita até esgotar a massa. Sirva depois as panquecas a gosto. Com compotas, creme de chocolate e avelãs, bacon, queijo e fiambre ou, como eu, iogurte e mel.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (39,'Petit gateau de caneca','Para o recheio, misture o chocolate derretido com o creme de leite até ficar homogêneo. Unte e enfarinhe 5 canecas de cerâmica com capacidade para 200ml. Bata no liquidificador o creme de leite, o leite condensado, os ovos, o chocolate, a manteiga e a farinha por 2 minutos. Adicione o fermento e misture com uma colher. Despeje metade da massa até atingir 1/3 da capacidade das canecas. Disponha 1 colher (sopa) do recheio e cubra com a massa restante até 2/3 da capacidade da caneca. Asse 1 caneca por vez no micro-ondas em temperatura média por 3 minutos ou até firmar na lateral e o centro ficar ligeiramente mole. Se preferir sirva acompanhado de 1 bola de sorvete de creme.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (40,'Bolinhos de banana','Pré-aqueça o forno a 180°C. Bata a manteiga e o açúcar até formar um creme. Adicione o ovo e continue a bater até obter uma mistura leve e fofa. Numa tigela, misture as bananas amassadas e o bicarbonato de sódio. Deixe descansar por 2 minutos. Misture a mistura de banana à mistura de manteiga. Misture a farinha, o sal e as especiarias e peneire a mistura da manteiga e banana. Deite na massa as nozes (ou raspas de chocolate). Deite a mistura em formas. Asse durante 11 a 13 minutos ou até ficar bem dourada. Deixe esfriar sobre uma grade.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (41,'Tarte de chocolate','Coloque o chocolate e a manteiga a derreter em banho-maria. Bata as claras até formarem picos e acrescente metade do açúcar aos bocados. Noutra tigela bata as gemas e o resto do açúcar, junte às gemas o chocolate, a farinha, a canela e a água. Envolve as claras aos bocados. Deite o preparado numa forma de tarte e leve ao forno pré-aquecido a 180º durante 25 minutos.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (42,'Empanadinhos de frango com coentros e parmesão','Comece por temperar os bifinhos de frango com o sal, a pimenta, o sumo de limão, os dentes de alho picadinhos e o vinho branco. Deixe a marinar um mínimo de 30 minutos. Entretanto mistura numa taça o pão ralado, os coentros picados e o parmesão. Em outra taça bata o ovo. Aqueça uma frigideira com um pouco de azeite ou óleo vegetal. Retire os bifinhos de frango da marinada escorrendo o excesso de líquido. Passe-os depois pelo ovo batido e em último lugar pela mistura de pão ralado. Frite-os depois em óleo quente, de ambos os lados até ficarem dourados. Para ficar excelente, sirva com um arroz de legumes e uma salda verde.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (43,'Pudim de Laranja simples','Mistura-se a farinha com o açúcar e junta-se-lhe os ovos batendo tudo durante alguns minutos. Junta-se o sumo de laranja e leva-se a cozer no forno em banho-maria durante 1 hora numa forma caramelizada.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (44,'Peru salteado com cogumelos e mozarella','Comece por limpar e laminar os cogumelos e reserve. Descasque em seguida os dentes de alho e lamine-os e corte os bifinhos de peru em tirinhas. Leve uma frigideira ao lume com um pouco de azeite. Junte os dentes de alho e deixe começarem a fritar. Acrescente depois os cogumelos e deixe-os saltear até que comecem a ganhar cor. Tempere com sal e pimenta e deixe cozinhar. Retire os cogumelos  reserve. Na mesma frigideira, e sem limpar, acrescente um pouco mais de azeite e salteie agora as tirinhas de peru, temperando-as também com sal e pimenta. Assim que estiverem cozinhadas, acrescente os cogumelos e os oregãos e envolva bem. Junte agora a mozarella cortada em cubinhos e deixe cozinhar até que o queijo derreta. Sirva com arroz ou massa.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (45,'Oreo com brigadeiro de chocolate','Coloque todos os ingredientes em uma panela e leve ao fogo por ao fogo até a mistura estar soltando da panela. Retire da panela e leve para gelar. Enrole um pouco do brigadeiro na mão e coloque as bolachas de Oreo como a foto, passar no granulado e servir.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (46,'Empadinhas de frango','Para a massa, coloque numa taça a água tépida, o vinho branco, a manteiga, um pouco de sal e a levedura seca. Misture bem até que tudo se dissolva mais ou menos. Junte depois a farinha e o ovo inteiro e amasse bem durante alguns minutos até obter uma bola de massa lisa e elástica (poderá amassar com a batedeira usado para isso as pás próprias). Forme uma bola, coloque numa taça, tape com um pano e deixe repousar 30 minutos. Prepare depois o recheio. Pique finamente a cebola e os dentes de alho e leve-os a alourar num pouco de azeite. Acrescente depois o frango desfiado e o vinho branco,  envolvendo bem, e deixe cozinhar uns minutos no refogado. Polvilhe depois com a farinha e acrescente o leite de modo a ficar com um recheio cremoso. Retifique de sal e pimenta e tempere a gosto com a noz moscada. Reserve e deixe arrefecer completamente antes de usar. Retire cerca de 2/3 da massa e divida-a em 12 pedaços iguais. Estenda com a ajuda de um rolo e forre 12 forminhas de empadas ou queques que deverá untar com um pouco de manteiga. Divida depois o recheio pelas 12 empadas. Com a restante massa, volte a dividir em 12 pedaços e estique-os para formar as tampas das empadas.Coloque sobre a massa recheada e feche bem as duas massas pressionando com a ponta dos dedos. Pincele depois as empadinhas com um pouco de leite ou até de gema de ovo batida e leve a cozinhar no forno previamente aquecido a 180ºC durante cerca de 25 minutos ou até que as empadas estejam bem cozinhadas e douradas. Retire do forno e deixe arrefecer completamente antes de desenformar. Se quiser poderá também congelar as empadinhas depois de prontas.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (47,'Salada asiática','Comece por picar finamente o pimentão vermelho, os tailos de aipo, a cebola vermelha e o coentro ou a salsinha e rala as cenouras. Em seguida misture todos os ingredientes do molho em uma tigela pequena e misture. Ponha de lado. Misture todos os ingredientes restantes juntos em uma tigela de tamanho médio. Despeje o molho sobre os ingredientes e misture bem. Sirva');
insert into Receita (id_receita,nome_receita,modopreparo ) values (48,'Pudim de leite condensado que não vai ao forno','Comece por bater as duas latas de leite condensado, o creme de leite e o leite fervendo. Coloque a gelatina diluída conforme a embalagem e bata por uns 3 minutos. Coloque em uma forma caramelizada e leve à geladeira por 3 horas. Desenforme e sirva. O tempo de preparo é de aproximadamente 30 min + 3 horas de geladeira.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (49,'Cheesecake de lima limão com frutos vermelhos','Comece por picar as bolachas juntamente com a manteiga até obter umas migalhas grossas. Forre o fundo de uma forma de mola com esta mistura, pressionando bem. Leve ao frigorifico a prender. Entretanto misture o queijo creme com o leite condensado até ficar bem misturado. Junte depois a raspa e o sumo da lima e do limão. Misture bem (a mistura vai começar a ficar mais grossa!) e verta este preparado sobre a base de bolacha e alise bem. Leve novamente ao frigorífico para prender. Antes de servir coloque a compota sobre o cheesecake espalhando bem sobre toda a superfície e decore com as framboesas frescas. Sirva de imediato.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (50,'Brigadeiro de champanhe com Kinder Bueno','Em uma panela misture todos os ingredientes e leve ao fogo aproximadamente por 40 minutos ou até que esteja bem firme. Retire da panela e leve para gelar por 2 horas para ficar firme. Com uma colher pegue um pouco de Brigadeiro e coloque na mão. Enrole e coloque o Kinder no meio e deixe em formato de "bolinha". Passe no chocolate em raspas e sirva.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (51,'Bolo gelado de coco','Massa: Bata as claras em neve até ao ponto de picos firmes (velocidade média da batedeira). Acrescente as gemas e continue batendo. Junte o açúcar, diminua a velocidade e cubra a batedeira com um pano para não se sujar. Misture a farinha, o leite e, por último, coloque o fermento. Despeje a massa numa assadeira retangular (15 cm x 30 cm) untada e enfarinhada. Leve ao forno médio por 40 min ou até dourar. Retire do forno, deixe esfriar e corte em quadrados de 5 cm x 5 cm. Reserve. Para a calda: Numa vasilha, misture o leite de coco, o leite, o açúcar e o coco ralado Molhe cada pedaço do bolo com 3 colheres de sopa da mistura do coco. Para a montagem: Embrulhe os pedaços um a um em papel-alumínio. Leve à geladeira por 2 horas ou deixe de um dia para o outro.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (52,'Profiteroles com sorvete','Massa: Em uma panela, misture a manteiga, a água e o sal e aqueça até a manteiga derreter. Deixe levantar fervura e desligue em seguida. Depois junte a farinha toda de uma vez e bata vigorosamente com a colher, até a massa se soltar das paredes da panela. Volte a levar panela ao fogo e continue a bater em fogo baixo durante cerca de 30 segundos, só para secar a bola de massa. Junte os ovos, um de cada vez, mexendo bem após cada adição até que a massa fique brilhante e macia. Unte uma assadeira e peneire farinha de trigo. Faça bolinhas (do tamanho que desejar) com a massa e coloque-as na assadeira. Pincele-as com gema de ovo. Asse em forno pré-aquecido durante 25 a 30 minutos. Quando as bombinhas estiverem prontas, corte-as horizontalmente. Encha as bombinhas cortadas com o sorvete de creme e empilhe-as em uma travessa rasa. Calda: Derreta o chocolate em banho-maria e em seguida adicione o creme de leite. Mantenha essa calda aquecida. Despeje por cima das bombinhas e sirva imediatamente.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (53,'Brownie de chocolate com recheio de sorvete','Na batedeira, coloque a manteiga, o açúcar e bata até ficar cremoso. Sem desligar a batedeira, adicione os ovos, um de cada vez. Acrescente o chocolate em pó e aos poucos vá juntando a farinha e o leite. Em seguida, Junte a essência de baunilha e o sal. Por último, adicione o fermento e o bicarbonato e bata até a massa ficar homogénea. Unte uma assadeira e forre com papel manteiga. Despeje a massa e asse em forno pré-aquecido a 180ºC. Deixe esfriar. Para a montagem, com uma faca ou uma linha, divida a massa ao meio. Passe uma camada espessa de sorvete numa metade da massa e cubra com a outra. Leve ao freezer por, no mínimo, 1 hora. Retire do freezer e corte o sanduíche em seis quadrados iguais. Espete um palito em cada sanduichinho e leve ao freezer. Pique ou rale o chocolate hidrogenado, derreta-o em banho maria e banhe os sanduíches nele. Você não vai usar todo o chocolate, mas é preciso ter volume suficiente para mergulhar os sanduíches. Coloque-os em uma assadeira forrada com papel-manteiga e leve ao freezer por cerca de 1 hora, até que a cobertura fique sólida. ');
insert into Receita (id_receita,nome_receita,modopreparo ) values (54,'Mini-charlotte de morango','Em água fria amoleça a gelatina e lave e limpe os morangos. Corte metade dos morangos em fatias finas. Forre 6 Taças de 200 ml cada com película e com as fatias de morango do género de telhas. Esmague os restantes morangos em puré e misture com o mascarpone, o açúcar e o sumo de limao. Em seguida, esprema e dissolva a gelatina a morno. Misture 1 colher de sopa de creme na gelatina e mexa. Junte a gelatina misturada ao resto do creme e misture. Bata as natas em castelo e envolva com o creme. Encha as taças até um pouco abaixo da borda com o creme e derreta a manteiga. Esmague os ameretti e os palitos la reine e misture com a manteiga derretida. Espalhe esta massa sobre as taças e pressione levemente. Leve ao frio durante cerca de 12 horas. Em seguida, desenforme sobre pratos de sobremesa, decore com morangos para dar aquele toque gourmet e sirva.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (55,'Gelato de leite condensado','Retire as gemas dos ovos, passe na peneire e reserve as claras. Numa panela misture o leite condensado, o leite e as gemas do ovo. Mexa no fogo até engrossar. Quando estiver grosso, deixar esfriar. Numa forma grande de buraco no meio, faça uma calda de açúcar queimado (4 colheres de açúcar). Misture 9 colheres de água com o chocolate em pó num copo e despeje sobre a calda de açúcar queimada. Em seguida, bata as claras em neve. Juntar 5 colheres de açúcar, faça um suspiro bem batido e misture delicadamente ao creme já frio. Despeje o creme na forma com a calda. Leve ao congelador ou freezer durante 9 horas. Na hora de servir, desenforme, colocar a forma por alguns minutos em uma bacia com um pouco de água.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (56,'Sorvete de limão','Coloque a água, juntamente com o açúcar, a ferver. Em seguida, esprema o limão e adicione o sumo ao preparado. Retire do lume e deixe arrefecer. Deixe a repousar durante 2 horas no congelador, para que ganhe consistência. Quando pretender servir, retire do congelador uma hora antes e adicione a clara batida em castelo, de forma a ficar bem firme. Leve novamente ao congelador durante mais 30 minutos. Após esse tempo retire do congelador e sirva de imediato.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (57,'Gelato de abacaxi','Comece por cortar o abacaxi em pedaços pequenos. Em seguida, misture todos os ingredientes numa tigela, excepto a gelatina. Siga as instruções na embalagem para dissolver a gelatina e quando estiver pronta misture a gelatina aos ingredientes já misturados anteriormente. Leve a geladeira por 2 horas antes de servir e sirva acompanhado com o que desejar.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (58,'Gelado de banana','Corte as bananas em rodelas e coloque-as no congelador para congelar. Após uma ou duas horas no congelador, e se as bananas estiverem, de facto, congeladas, coloque-as juntamente com a farinha de castanha, o leite, o mel e o creme de leite no liquidificador. Bata tudo até não sobrar nenhum pedaço de banana inteiro. Depois é só colocar em algum recipiente para gelado, levar ao congelador e esperar duas horas.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (59,'Balas de caramelo caseiras','Passe o açúcar branco e mascavo pela peneira e misture com o restante dos ingredientes em uma tigela grande. Leve ao microondas em potência alta de 9 a 10 minutos (Meu microondas é da marca Brastemp e fiz em potência alta, mas pode variar de marca para marca). (A tigela deve ser grande, pois ao ferver triplica de volume). Mexa de 2 em 2 minutos para misturar bem os ingredientes. Ao final do tempo a mistura estará bem borbulhante e homogênea, parecido com brigadeiro quando desgruda do fundo da panela. Despeje em um refratário ou forma untada com margarina, polvilhe o coco ralado e quando estiver morno retire e corte os caramelos com uma faca.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (60,'Bolo úmido de chocolate e nozes','Ligue o forno a 180ºC e forre uma forma retangular com papel vegetal e reserve. Parta o chocolate em pedaços e derreta-o em banho-maria o no micro-ondas. Mexa bem e reserve. Bata a manteiga com o açúcar até obter um creme macio. Junte as gemas, uma a uma, batendo sempre. Acrescente o chocolate derretido e bata mais um pouco. Adicione a farinha, o fermento e as nozes partidas em pedaços, envolvendo bem. Reserve. À parte, bata as claras em castelo e adicione metade delas ao preparado anterior. Misture muito bem, incorpore as restantes claras e envolva delicadamente. Deite a massa na forma e leve ao forno durante 30 minutos. Verifique a cozedura com um palito, se este sair molhado, com a massa tipo creme, o bolo estará pronto. Retire o bolo do forno e deixe arrefecer, antes de desenformar e retirar o papel. Para a cobertura, leve as natas ao lume e deixe ferver. Junte o chocolate em pedaços e deixe repousar cerca de 1o minutos. Mexa bem o creme de chocolate, deixe arrefecer e cubra o bolo com ele. Decore com as metades de noz. Sirva o bolo bem simples ou acompanhado de uma bola de gelado a gosto.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (61,'Brownies numa caneca','Coloque a farinha, o açúcar, o cacau, o sal e a canela numa caneca de cerâmica que possa ir ao microondas. Mexa com um garfo ou colher para misturar bem e acabar com qualquer aglomerados. Adicione o óleo, a água e a baunilha ao copo e mexa até a mistura ficar lisa e sem nódulos. Coloque no microondas e aqueça até que a mistura estar cozida, cerca de 1 minuto e 40 segundos num microondas de 1000 watts. Você pode ter que experimentar e ajustar o tempo de microondas. Se você não sabe o nível de potência do seu micro-ondas, comece com 60 segundos, e aumente até o brownie estar feito. Ele ainda deve estar húmido quando cozido, não seco. Deixe esfriar um minuto e sirva com uma bola de gelado de baunilha ou derrame uma ou duas colheres de chá de creme de leite.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (62,'Crepes com molho de chocolate','Misture a farinha com uma pitada de sal e açúcar. Junte o leite e o ovo, previamente misturados, mexendo com uma vara de arames. Adicione a margarina, derretida na frigideira em que vai fazer os crepes. Deixe a massa repousar cerca de 30 minutos antes de começar a cozer os crepes e entretanto vá preparando o molho de chocolate. Numa taça deite a margarina aos bocadinhos, o açúcar, o chocolate partido em quadradinhos e o café quente. Leve a derreter no micro ondas durante 1 minuto na potência máxima, ou sobre o lume em banho maria. Mexa com uma vara de arames para ligar todos os ingredientes até ficar com um molho liso e uniforme. Sirva os crepes barrados com o molho de chocolate, dobrados em 4, e acompanhe com gelado, uma bola de chocolate e outra de nata.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (63,'Costelinha assada ao molho barbecue','Tempere a costelinha com sal, pimenta e embrulhe em papel alumínio. Leve ao forno médio, preaquecido, por 30 minutos. Retire e reserve. Bata todos os ingredientes do molho no liquidificador, despeje em uma panela e leve ao fogo baixo, mexendo sem parar, por 15 minutos ou até engrossar levemente. Tempere as batatas com sal, pimenta, o azeite, o alecrim, o alho e coloque em uma forma untada e leve ao forno médio, preaquecido, por 20 minutos. Reserve. Retire o papel alumínio da costelinha, coloque 1/3 do molho e leve ao forno baixo, preaquecido, por 15 minutos. Retire do forno, regue com 1/3 do molho e leve ao forno baixo, preaquecido, por 15 minutos. Retire do forno, regue com 1/3 do molho, volte ao forno e asse por mais 20 minutos. Retire, cubra com o restante do molho e asse por mais 20 minutos. Retire do forno e sirva acompanhada de batata com alecrim.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (64,'Biscoitinhos de leite condensado','Em uma tigela, misture a lata de leite condensado, a manteiga, a maizena e o fermento. Misture tudo. Vá adicionando maizena e mexendo até a massa ficar lisa e soltar das mãos. Faça um rolinho de massa e corte em quadradinhos. Você pode também usar forminhas de cortar biscoito ou cortar no formato que quiser. Coloque os biscoitos em uma forma untada com manteiga Leve ao forno por 15~20 minutos a 200 graus e feito!');
insert into Receita (id_receita,nome_receita,modopreparo ) values (65,'Panquecas de carne com queijo','Bata todos os ingredientes da massa no liquidificador por cerca de 5 minutos, até ter uma mistura bem homogênea. Em uma frigideira, coloque um fio de óleo apenas para untar e derrame um pouco a mistura da massa na frigideira, fazendo um círculo fino com a massa. Aguarde até o centro começar a perder a cor clara e vire a panqueca. Quando a panqueca estiver dourada dos dois lados, retire do fogão. Repita o processo com toda a massa restante. Em uma outra panela, misture a carne moída, temperos de sua preferência (utilizamos bastante Coentro) e adicione os cubinhos até começarem a derreter. Montagem: Separe as panquecas e uma por uma, vá adicionando a carne moída no meio e enrolando. Monte-as todas enfileiradas em um prato. Coloque por cima o molho de tomate.  Finalize com queijo parmesão ralado e sirva.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (66,'Bifinhos com manteiga e alho, espargos com bacon e feijão preto','Tempere os bifinhos com um pouco de sal e pimenta e reserve. Entretanto prepare os espargos, cortando a parte fibrosa do fundo, e leve-os a cozinhar 3 minutos em água a ferver, temperada de sal e pimenta. Escorra-os e reserve, deixando arrefecer. Lamine 2 dentes de alho e coloque-os numa frigideira juntamente com a manteiga e uma folha de louro. Deixe a manteiga derreter e acrescente os bifinhos deixando-os cozinhar de ambos os lados até estarem cozinhados a seu gosto, mais ou menos passados. Entretanto enrole as fatias de bacon nos espargos e leve-os a grelhar numa chapa com um fio de azeite, até que o bacon esteja crocante e os espargos cozinhados. Se gostar tempere com uma pitada de pimenta moída na hora. Para o feijão preto, leve um tachinho ao lume com um dente de alho bem picado, o pimento vermelho em cubinhos, o louro e o chouriço ou bacon em pequenos pedaços. Acrescente um fio de azeite e deixe que o chouriço comece a fritar e a libertar a sua gordura. Acrescente depois o feijão preto, envolva bem, retifique os temperos e deixe ferver cerca de 5 minutos para apurar. Sirva os bifinhos com os espargos e o feijão preto e acompanhe com arroz branco e uma salada verde.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (67,'Smothie de banana, mel e manteiga de amendoim','Coloque todos os ingredientes no copo liquidificador e triture até obter uma consistência cremosa e aveludada. Sirva de imediato e se gostar polvilhe com canela.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (68,'Salsicha italiana grelhada com pimentão, cebola e rúcula','Pré-aqueça o grelhador. Misture o vinagre balsâmico e o mel numa tigela pequena e coloque de lado. Regue a cebola, o pimentão e as salsichas com um pouco de azeite, sal e pimenta. Unte o grelhador com um pouco de azeite. Coloque as fatias de cebola na grelha. Deixe as cebolas assar durante 5 minutos, ou até que elas estejam um pouco carbonizadas. Vire as cebolas e mova-as para uma parte mais frio da grelha para terminar. Se o seu grelhador tem dois níveis, coloque as salsichas na parte superior da grade e os pimentões diretamente abaixo deles. Feito desta forma, o suco de gotejamento das salsichas e a gordura vai cair no pimentão, temperando-o. Se o seu grelhador não tem dois níveis, coloque os pimentões na parte mais quente e as salsichas sobre o mais frio. Deixe grelhar durante 15 a 20 minutos ou mais, verificando periodicamente. No final, regue as salsichas, pimentas e cebolas com a mistura de mel e vinagre balsâmico que inicialmente preparou. Quando as salsichas, os pimentões e as cebolas estiverem grelhadas, retire-as da grelha para uma tigela grande. Corte os pimentões em tiras compridas, e corte a extremidade da raiz das cebolas. Corte as salsichas em três partes. Misture tudo muito bem na panela ou tigela. Para servir, coloque uma cama rúcula bebé nos pratos de servir e cubra com a linguiça, pimentão e cebola.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (69,'Bolo de Oreo com cobertura de brigadeiro de leite ninho','Numa tigela, coloque todos os ingredientes secos (chocolate, açúcar, fermento e farinha e a bolacha triturada). Misture e vá acrescentando, aos poucos, o restante dos ingredientes (leite, óleo e ovos). Leve ao forno pré-aquecido e asse por cerca de 25 minutos ou até dourar. Deixe esfriar e reserve. Brigadeiro de leite Ninho: Colocar todos os ingredientes em uma panela e levar ao fogo por 17 minutos, mexendo sem parar. Tire da panela, deixe esfriar e cubra o bolo.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (70,'Bolo Kit Kat','Bolo: Bata todos os ingredientes durante 5 minutos (menos o fermento). Em seguida, adicione o fermento e misture delicadamente com uma espátula. Coloque em uma forma untada e asse por 40 minutos Cobertura: Esquente o creme de leite no fogão mas não deixe ferver. Retire do fogo e adicione a barra de chocolate picada, vá mexendo até derreter o chocolate por completo. Montagem: Dependendo do tamanho do bolo, decore com a quantidade de Kit Kat necessários (em média uns 9 chocolates para que dê 36 tabletes). Com uma colher, passe o brigadeiro nos tabletes do chocolate kit kat e vá colando nas bordas do bolo. Quando terminar, jogue m&m por cima e sirva.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (71,'Panquecas de Natal','Bata o ovo com a farinha, o açúcar e o fermento. Junte depois o leite e metade do azeite e mexa bem até obter uma massa grossa. Leve uma frigideira anti aderente ao lume com o restante azeite e deixe aquecer. Coloque duas colheradas de massa de panquecas e deixe começar a formar bolinhas. Vire-a cuidadosamente e deixe cozinhar do outro lado até estar dourada. Repita até esgotar a massa. Para servir regue com o mel ou maple syrup e polvilhe generosamente com os bagos de romã e com algumas folhinhas de hortelã. Para uma experiência de natal completa, sirva com chocolate quente.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (72,'Quesadilla de frango e maçã','Aqueça uma frigideira grande em lume médio. Coloque uma tortilha na frigideira. Lance-a um par de vezes com uma espátula, em seguida, deixe descansar na panela e aquecer até formar bolsões de ar e partes da tortilla começarem a inchar. Lance-a novamente. Coloque fatias de queijo na metade da tortilla, pelo menos 1,2 cm a partir da borda da tortilla. Adicione os pedaços de frango em cima do queijo. Dobre a tortilla como uma omelete, e pressione a tortilla dobrada com a espátula. Abaixe o fogo para médio. Neste ponto, se você tiver espaço suficiente na sua frigideira, você pode adicionar uma segunda tortilla para a panela começar a aquecê-la. Quando o queijo dentro derreter, retire a quesadilla para uma tábua de corte. Abra-a e coloca a camada de maçã em fatias e a salsa. Dobre a tortilla novamente, e corte-a em três triângulos, como se estivesse a cortar uma torta. (Você não tem que cortar a quesadilla em triângulos, isso apenas torna mais fácil para as crianças comer). Repita os passos com as restantes quesadillas.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (73,'Sopa cremosa de abóbora','Comece por lavar e cortar todos os legumes em pedaços e salteie-os com as folhas de louro no Alpro Creme de soja para Cozinhar e Assar. Junte a água e os cubos de caldo de legumes e deixe cozinhar durante 45 minutos. Retire as folhas de louro, adicione a Alpro alternativa de soja às natas culinárias e triture tudo. Sirva quente.');
insert into Receita (id_receita,nome_receita,modopreparo ) values (74,'Molho de iogurte','Deitam-se todos os ingredientes na batedeira e batem-se até ficarem todos muito bem misturados. Servir imediatamente como acompanhamento ou molho.');
insert into receita(id_receita,nome_receita,modopreparo ) values (75,'abc','asgsdgsd');


insert into Composicao values(1,1,'100 gramas');
insert into Composicao values(1,2,'135 gramas');
insert into Composicao values(1,3,'2 unidades');
insert into Composicao values(1,4,'1 colher de chá');
insert into Composicao values(1,5,'1 colher de chá');
insert into Composicao values(1,6,'1 xícara de gotas');
insert into Composicao values(1,7,'2 xícaras');
insert into Composicao values(2,8,'3 peças');
insert into Composicao values(2,9,'a gosto');
insert into Composicao values(2,10,'tiras a gosto');
insert into Composicao values(2,11,'3 fatias');
insert into Composicao values(2,12,'3 fatias');
insert into Composicao values(2,3,'1 unidade');
insert into Composicao values(2,13,'1 xícara');
insert into Composicao values(2,14,'1 xícara');
insert into Composicao values(2,7,'1/2 xícara');
insert into Composicao values(3,15,'500 gramas');
insert into Composicao values(3,10,'8 unidades');
insert into Composicao values(3,16,'1 unidade');
insert into Composicao values(3,17,'4 dentes');
insert into Composicao values(3,18,'1 unidade');
insert into Composicao values(3,121,'a gosto');
insert into Composicao values(3,20,'a gosto');
insert into Composicao values(3,21,'a gosto');
insert into Composicao values(3,22,'a gosto');
insert into Composicao values(3,23,'180 gramas');
insert into Composicao values(3,24,'300 gramas');
insert into Composicao values(3,25,'a gosto');
insert into Composicao values(4,16,'2 unidades');
insert into Composicao values(4,9,'6 bifes');
insert into Composicao values(4,26,'1 unidade');
insert into Composicao values(4,20,'a gosto');
insert into Composicao values(4,121,'a gosto');
insert into Composicao values(4,10,'2 unidades');
insert into Composicao values(5,27,'3 unidades');
insert into Composicao values(5,16,'1 unidade');
insert into Composicao values(5,28,'1 unidade');
insert into Composicao values(5,21,'a gosto');
insert into Composicao values(5,28,'1,5 xícara');
insert into Composicao values(5,30,'1 unidade');
insert into Composicao values(6,29,'2 xícara');
insert into Composicao values(6,31,'1 unidade');
insert into Composicao values(6,32,'250 gramas');
insert into Composicao values(6,20,'a gosto');
insert into Composicao values(6,18,'a gosto');
insert into Composicao values(6,21,'a gosto');
insert into Composicao values(6,17,'1 unidade');
insert into Composicao values(6,33,'1 unidade');
insert into Composicao values(6,34,'1 pedaço');
insert into Composicao values(6,35,'1 ramo');
insert into Composicao values(7,16,'1 unidade');
insert into Composicao values(7,17,'1 unidade');
insert into Composicao values(7,21,'3 colher de sopa');
insert into Composicao values(7,29,'1 xícara');
insert into Composicao values(7,30,'1/2 litro');
insert into Composicao values(7,10,'175 gramas');
insert into Composicao values(7,36,'1/2 xícara');
insert into Composicao values(7,37,'8 unidades');
insert into Composicao values(7,38,'1/2 xícara em pedaços');
insert into Composicao values(7,39,'1/2 xícara em fatias');
insert into Composicao values(7,20,'a gosto');
insert into Composicao values(7,12,'a gosto');
insert into Composicao values(8,40,'1 unidade');
insert into Composicao values(8,17,'3 dentes');
insert into Composicao values(8,21,'a gosto');
insert into Composicao values(8,121,'1 ramo');
insert into Composicao values(9,3,'2 unidades');
insert into Composicao values(9,16,'2 colher de sopa');
insert into Composicao values(9,41,'2 colher de sopa');
insert into Composicao values(9,10,'2 colher de sopa');
insert into Composicao values(9,12,'2 colher de sopa');
insert into Composicao values(9,42,'2 fatias');
insert into Composicao values(9,35,'a gosto');
insert into Composicao values(9,121,'a gosto');
insert into Composicao values(9,43,'a gosto');
insert into Composicao values(9,21,'a gosto');
insert into Composicao values(9,44,'a gosto');
insert into Composicao values(9,20,'a gosto');
insert into Composicao values(9,18,'a gosto');
insert into Composicao values(10,14,'300 gramas');
insert into Composicao values(10,45,'250 ml');
insert into Composicao values(10,3,'1 unidade');
insert into Composicao values(10,16,'3 unidades');
insert into Composicao values(10,18,'a gosto');
insert into Composicao values(10,20,'a gosto');
insert into Composicao values(10,44,'a gosto');
insert into Composicao values(11,10,'2 quilos');
insert into Composicao values(11,2,'1 quilo');
insert into Composicao values(11,46,'1 unidade');
insert into Composicao values(11,26,'1 unidade');
insert into Composicao values(11,47,'2 unidades');
insert into Composicao values(12,10,'a gosto');
insert into Composicao values(12,12,'a gosto');
insert into Composicao values(12,48,'a gosto');
insert into Composicao values(12,49,'a gosto');
insert into Composicao values(12,27,'a gosto');
insert into Composicao values(12,50,'a gosto');
insert into Composicao values(12,20,'a gosto');
insert into Composicao values(12,18,'a gosto');
insert into Composicao values(12,121,'a gosto');
insert into Composicao values(13,3,'6 unidades');
insert into Composicao values(13,13,'1 colher de sopa');
insert into Composicao values(13,1,'1 colher de sopa');
insert into Composicao values(13,52,'a gosto');
insert into Composicao values(13,18,'a gosto');
insert into Composicao values(13,20,'a gosto');
insert into Composicao values(14,40,'a gosto');
insert into Composicao values(14,11,'a gosto');
insert into Composicao values(14,12,'a gosto');
insert into Composicao values(14,53,'a gosto');
insert into Composicao values(14,1,'1/2 xícara');
insert into Composicao values(14,50,'1 colher de sopa');
insert into Composicao values(14,54,'1 colher de sopa');
insert into Composicao values(14,16,'2 colher de sopa');
insert into Composicao values(14,25,'1/4 xícara');
insert into Composicao values(14,55,'2 colher de sopa');
insert into Composicao values(15,56,'5 colheres de sopa');
insert into Composicao values(15,3,'4 unidades');
insert into Composicao values(15,44,'a gosto');
insert into Composicao values(15,11,'4 fatias');
insert into Composicao values(15,1,'135 gramas');
insert into Composicao values(15,40,'4 fatias');
insert into Composicao values(15,57,'a gosto');
insert into Composicao values(15,20,'a gosto');
insert into Composicao values(15,121,'a gosto');
insert into Composicao values(16,27,'1 unidade');
insert into Composicao values(16,48,'2 colheres de sopa');
insert into Composicao values(16,28,'2 colheres de sopa');
insert into Composicao values(16,54,'1,5 colher de sopa');
insert into Composicao values(17,8,'2 peitos');
insert into Composicao values(17,19,'2 talos');
insert into Composicao values(17,48,'3 colheres de sopa');
insert into Composicao values(17,16,'1/2 unidade');
insert into Composicao values(17,58,'a gosto');
insert into Composicao values(17,20,'a gosto');
insert into Composicao values(17,18,'a gosto');
insert into Composicao values(17,121,'a gosto');
insert into Composicao values(18,42,'a gosto');
insert into Composicao values(18,31,'a gosto');
insert into Composicao values(18,59,'a gosto');
insert into Composicao values(18,10,'a gosto');
insert into Composicao values(18,20,'a gosto');
insert into Composicao values(18,48,'a gosto');
insert into Composicao values(19,10,'a gosto');
insert into Composicao values(19,21,'a gosto');
insert into Composicao values(19,62,'a gosto');
insert into Composicao values(19,61,'a gosto');
insert into Composicao values(19,20,'a gosto');
insert into Composicao values(19,60,'fatias a gosto');
insert into Composicao values(20,63,'200 gramas');
insert into Composicao values(21,64,'uma porção');
insert into Composicao values(21,65,'uma porção');
insert into Composicao values(21,66,'a gosto');
insert into Composicao values(22,3,'6 unidades');
insert into Composicao values(22,2,'1/2 xícara de chá');
insert into Composicao values(22,7,'1/2 xícara');
insert into Composicao values(22,67,'1/2 colher de sopa');
insert into Composicao values(22,68,'1 quilo');
insert into Composicao values(22,69,'1/2 xícara');
insert into Composicao values(23,3,'4 unidades');
insert into Composicao values(23,6,'240 gramas');
insert into Composicao values(24,3,'6 undiades');
insert into Composicao values(24,6,'320 gramas');
insert into Composicao values(25,3,'4 unidades');
insert into Composicao values(25,2,'200 gramas');
insert into Composicao values(25,51,'150 gramas');
insert into Composicao values(25,7,'200 gramas');
insert into Composicao values(25,70,'100 gramas');
insert into Composicao values(25,67,'1 colher de chá');
insert into Composicao values(25,63,'100 gramas');
insert into Composicao values(26,63,'12 porções');
insert into Composicao values(26,3,'4 unidades');
insert into Composicao values(26,2,'120 gramas');
insert into Composicao values(27,71,'a gosto');
insert into Composicao values(27,2,'a gosto');
insert into Composicao values(28,1,'125 gramas');
insert into Composicao values(28,2,'1/3 xícara');
insert into Composicao values(28,72,'1/2 xícara');
insert into Composicao values(28,3,'1 unidade');
insert into Composicao values(28,51,'2 colher de chá');
insert into Composicao values(28,7,'2 xícaras');
insert into Composicao values(28,20,'1/2 colher');
insert into Composicao values(28,63,'uma porção');
insert into Composicao values(28,13,'1,5 copo');
insert into Composicao values(29,73,'200 gramas');
insert into Composicao values(29,44,'a gosto');
insert into Composicao values(29,20,'a gosto');
insert into Composicao values(30,74,'1 quilo');
insert into Composicao values(30,26,'2 unidades');
insert into Composicao values(30,46,'2 unidades');
insert into Composicao values(30,72,'1/4 xícara');
insert into Composicao values(30,2,'1/4 xícara');
insert into Composicao values(30,20,'1 colher de chá');
insert into Composicao values(31,75,'2 quilos');
insert into Composicao values(31,71,'2 laranjas');
insert into Composicao values(31,76,'100 gramas');
insert into Composicao values(31,34,'50 gramas');
insert into Composicao values(31,2,'1400 gramas');
insert into Composicao values(32,29,'150 gramas');
insert into Composicao values(32,77,'125 ml');
insert into Composicao values(32,78,'500 ml');
insert into Composicao values(32,18,'a gosto');
insert into Composicao values(32,20,'a gosto');
insert into Composicao values(32,21,'2 colher de sopa');
insert into Composicao values(32,16,'1 unidade');
insert into Composicao values(32,75,'1 unidade');
insert into Composicao values(32,79,'75 gramas');
insert into Composicao values(32,25,'50 gramas');
insert into Composicao values(33,80,'128 gramas');
insert into Composicao values(33,81,'1 barra');
insert into Composicao values(33,6,'2 colher de sopa');
insert into Composicao values(33,13,'2 xícaras');
insert into Composicao values(33,82,'1 unidade');
insert into Composicao values(33,51,'1 colher de chá');
insert into Composicao values(33,63,'150 gramas');
insert into Composicao values(34,3,'4 unidades');
insert into Composicao values(34,26,'2 unidades');
insert into Composicao values(34,83,'125 ml');
insert into Composicao values(34,1,'200 gramas');
insert into Composicao values(34,2,'400 gramas');
insert into Composicao values(34,7,'150 gramas');
insert into Composicao values(34,84,'150 gramas');
insert into Composicao values(34,67,'1 colher de chá');
insert into Composicao values(35,82,'395 gramas');
insert into Composicao values(35,2,'1 xícara');
insert into Composicao values(35,13,'1 xícara');
insert into Composicao values(36,85,'350 gramas');
insert into Composicao values(36,23,'200 gramas');
insert into Composicao values(36,20,'a gosto');
insert into Composicao values(36,18,'a gosto');
insert into Composicao values(36,17,'2 dentes');
insert into Composicao values(36,21,'a gosto');
insert into Composicao values(36,24,'200 gramas');
insert into Composicao values(36,86,'150 ml');
insert into Composicao values(37,87,'1 quilo');
insert into Composicao values(37,2,'1 quilo');
insert into Composicao values(38,88,'100 gramas');
insert into Composicao values(38,89,'50 gramas');
insert into Composicao values(38,3,'1 unidade');
insert into Composicao values(38,46,'1 unidade');
insert into Composicao values(38,67,'1 colher de chá');
insert into Composicao values(38,90,'1 colher de sopa');
insert into Composicao values(39,63,'1 xícara');
insert into Composicao values(39,69,'1 unidade');
insert into Composicao values(39,82,'1 unidade');
insert into Composicao values(39,3,'3 unidades');
insert into Composicao values(39,1,'2 colher de sopa');
insert into Composicao values(39,7,'3 colher de sopa');
insert into Composicao values(39,67,'1/2 colher de chá');
insert into Composicao values(39,64,'1 porção');
insert into Composicao values(40,1,'1/2 xícara');
insert into Composicao values(40,2,'1 xícara');
insert into Composicao values(40,3,'1 unidade');
insert into Composicao values(40,91,'1 unidade');
insert into Composicao values(40,5,'1 colher de chá');
insert into Composicao values(40,7,'2 xícaras');
insert into Composicao values(40,20,'a gosto');
insert into Composicao values(40,46,'1/2 colher de chá');
insert into Composicao values(40,74,'1/2 colher de chá');
insert into Composicao values(40,47,'1/2 colher de chá');
insert into Composicao values(40,92,'1 xícara');
insert into Composicao values(41,63,'200 gramas');
insert into Composicao values(41,1,'100 gramas');
insert into Composicao values(41,3,'5 unidades');
insert into Composicao values(41,67,'1/2 colher de chá');
insert into Composicao values(41,2,'175 gramas');
insert into Composicao values(41,7,'175 gramas');
insert into Composicao values(41,46,'1/2 colher de chá');
insert into Composicao values(42,8,'2 peitos');
insert into Composicao values(42,26,'1 unidade');
insert into Composicao values(42,20,'a gosto');
insert into Composicao values(42,18,'a gosto');
insert into Composicao values(42,3,'1 unidade');
insert into Composicao values(42,77,'50 ml');
insert into Composicao values(42,35,'4 colheres de sopa');
insert into Composicao values(42,25,'4 colheres de sopa');
insert into Composicao values(43,2,'400 gramas');
insert into Composicao values(43,3,'8 unidades');
insert into Composicao values(43,7,'1 colher de chá');
insert into Composicao values(43,71,'1 unidade');
insert into Composicao values(44,23,'200 gramas');
insert into Composicao values(44,93,'350 gramas');
insert into Composicao values(44,17,'2 dentes');
insert into Composicao values(44,21,'a gosto');
insert into Composicao values(44,18,'a gosto');
insert into Composicao values(44,20,'a gosto');
insert into Composicao values(44,49,'1 colher de sopa');
insert into Composicao values(44,12,'1 porção');
insert into Composicao values(45,82,'2 unidades');
insert into Composicao values(45,69,'1/2 unidade');
insert into Composicao values(45,63,'300 gramas');
insert into Composicao values(46,7,'300 gramas');
insert into Composicao values(46,3,'1 unidade');
insert into Composicao values(46,77,'40 ml');
insert into Composicao values(46,1,'30 gramas');
insert into Composicao values(46,20,'a gosto');
insert into Composicao values(46,8,'450 gramas');
insert into Composicao values(46,16,'1 unidade');
insert into Composicao values(46,17,'2 dentes');
insert into Composicao values(46,21,'a gosto');
insert into Composicao values(46,18,'a gosto');
insert into Composicao values(46,20,'a gosto');
insert into Composicao values(46,77,'40 ml');
insert into Composicao values(46,7,'2 colher de sopa');
insert into Composicao values(46,13,'150 ml');
insert into Composicao values(47,41,'2 unidades');
insert into Composicao values(47,94,'1 unidade');
insert into Composicao values(47,19,'2 talos');
insert into Composicao values(47,16,'1/4 unidade');
insert into Composicao values(47,35,'1/4 xícara');
insert into Composicao values(47,95,'2 colher de sopa');
insert into Composicao values(47,97,'1/4 xícara');
insert into Composicao values(47,96,'2 colher de sopa');
insert into Composicao values(47,26,'1 colher de sopa');
insert into Composicao values(47,90,'1 colher de sopa');
insert into Composicao values(47,34,'1 colher de chá');
insert into Composicao values(47,61,'2 colher de chá');
insert into Composicao values(47,17,'1 dente');
insert into Composicao values(47,20,'a gosto');
insert into Composicao values(48,82,'2 unidades');
insert into Composicao values(48,13,'1 xícara');
insert into Composicao values(48,69,'3 unidades');
insert into Composicao values(48,80,'2 unidades');
insert into Composicao values(49,66,'300 gramas');
insert into Composicao values(49,1,'50 gramas');
insert into Composicao values(49,81,'350 gramas');
insert into Composicao values(49,82,'1 unidade');
insert into Composicao values(49,33,'1 unidade');
insert into Composicao values(49,26,'1 unidade');
insert into Composicao values(49,98,'uma porção');
insert into Composicao values(49,99,'250 gramas');
insert into Composicao values(50,82,'3 unidades');
insert into Composicao values(50,69,'1 unidade');
insert into Composicao values(50,20,'a gosto');
insert into Composicao values(50,100,'100 gramas');
insert into Composicao values(50,1,'1 colher de sopa');
insert into Composicao values(50,101,'100 ml');
insert into Composicao values(51,3,'5 undiades');
insert into Composicao values(51,7,'2 xícaras');
insert into Composicao values(51,2,'3 xícaras');
insert into Composicao values(51,13,'3 xícara');
insert into Composicao values(51,67,'1/2 colher de sopa');
insert into Composicao values(51,102,'300 ml');
insert into Composicao values(52,20,'1 colher de chá');
insert into Composicao values(52,1,'6 colher de sopa');
insert into Composicao values(52,7,'3 xícaras');
insert into Composicao values(52,3,'4 unidades');
insert into Composicao values(52,64,'uma porção');
insert into Composicao values(52,69,'1 unidade');
insert into Composicao values(52,63,'200 gramas');
insert into Composicao values(53,1,'400 gramas');
insert into Composicao values(53,2,'130 gramas');
insert into Composicao values(53,63,'1 quilo');
insert into Composicao values(53,3,'6 unidades');
insert into Composicao values(53,7,'360 gramas');
insert into Composicao values(53,67,'15 gramas');
insert into Composicao values(53,5,'15 gramas');
insert into Composicao values(53,20,'a gosto');
insert into Composicao values(53,13,'400 ml');
insert into Composicao values(53,4,'20 ml');
insert into Composicao values(53,64,'1,5 L');
insert into Composicao values(54,80,'6 unidades');
insert into Composicao values(54,103,'500 gramas');
insert into Composicao values(54,104,'250 gramas');
insert into Composicao values(54,2,'açúcar');
insert into Composicao values(54,26,'1 unidade');
insert into Composicao values(54,86,'200 gramas');
insert into Composicao values(54,1,'120 gramas');
insert into Composicao values(54,66,'50 gramas');
insert into Composicao values(55,82,'1 unidade');
insert into Composicao values(55,13,'2 unidades');
insert into Composicao values(55,3,'3 unidades');
insert into Composicao values(55,2,'9 colheres de sopa');
insert into Composicao values(55,63,'4 colheres de sopa');
insert into Composicao values(56,26,'2 colheres de chá');
insert into Composicao values(56,2,'250 gramas');
insert into Composicao values(56,3,'1 unidade');
insert into Composicao values(57,105,'2 unidades');
insert into Composicao values(57,82,'1 undiade');
insert into Composicao values(57,69,'2 unidades');
insert into Composicao values(57,80,'1/2 unidade');
insert into Composicao values(58,91,'3 unidades');
insert into Composicao values(58,106,'60 gramas');
insert into Composicao values(58,13,'1/2 copo');
insert into Composicao values(58,90,'2 colheres de sopa');
insert into Composicao values(58,69,'3 colheres de sopa');
insert into Composicao values(59,72,'1 xícara');
insert into Composicao values(59,2,'1 xícara');
insert into Composicao values(59,82,'1 xícara');
insert into Composicao values(59,1,'1/2 xícara');
insert into Composicao values(59,107,'3 colheres');
insert into Composicao values(60,67,'1 colher de chá');
insert into Composicao values(60,92,'100 gramas');
insert into Composicao values(60,7,'150 gramas');
insert into Composicao values(60,2,'200 gramas');
insert into Composicao values(60,63,'400 gramas');
insert into Composicao values(60,1,'200 gramas');
insert into Composicao values(60,3,'6 unidades');
insert into Composicao values(60,86,'100 ml');
insert into Composicao values(61,7,'1/4 xícara');
insert into Composicao values(61,2,'70 gramas');
insert into Composicao values(61,108,'2 colheres de sopa');
insert into Composicao values(61,20,'a gosto');
insert into Composicao values(61,46,'a gosto');
insert into Composicao values(61,44,'2 colheres de sopa');
insert into Composicao values(61,4,'2 gotas');
insert into Composicao values(61,64,'2 colheres de chá');
insert into Composicao values(62,7,'100 gramas');
insert into Composicao values(62,63,'200 gramas');
insert into Composicao values(62,1,'30 gramas');
insert into Composicao values(62,2,'3 colheres de sopa');
insert into Composicao values(62,20,'a gosto');
insert into Composicao values(62,13,'1/2 copo');
insert into Composicao values(62,3,'2 unidades');
insert into Composicao values(63,10,'1 xícara');
insert into Composicao values(63,56,'2 colheres de sopa');
insert into Composicao values(63,72,'1 colher de sopa');
insert into Composicao values(63,90,'1 colher de sopa');
insert into Composicao values(63,16,'1 unidade');
insert into Composicao values(63,17,'3 dente');
insert into Composicao values(63,111,'1/2 colher de chá');
insert into Composicao values(63,112,'1 unidade');
insert into Composicao values(63,28,'2 colheres de sopa');
insert into Composicao values(63,113,'6 unidades');
insert into Composicao values(63,20,'a gosto');
insert into Composicao values(63,18,'a gosto');
insert into Composicao values(63,21,'3 colheres de sopa');
insert into Composicao values(63,109,'2 colheres de sopa');
insert into Composicao values(63,110,'2,5 quilos');
insert into Composicao values(64,82,'1/2 unidade');
insert into Composicao values(64,114,'250 gramas');
insert into Composicao values(64,1,'100 gramas');
insert into Composicao values(64,67,'1/4 colher de sopa');
insert into Composicao values(65,84,'1 xícara');
insert into Composicao values(65,13,'1 xícara');
insert into Composicao values(65,44,'1 colher de sopa');
insert into Composicao values(65,3,'1 unidade');
insert into Composicao values(65,20,'a gosto');
insert into Composicao values(65,15,'uma porção');
insert into Composicao values(65,25,'100 gramas');
insert into Composicao values(65,28,'a gosto');
insert into Composicao values(66,85,'4 bifes');
insert into Composicao values(66,17,'3 dentes');
insert into Composicao values(66,112,'2 unidades');
insert into Composicao values(66,20,'a gosto');
insert into Composicao values(66,18,'1/4 unidade');
insert into Composicao values(66,115,'1 lata');
insert into Composicao values(66,116,'8 unidades');
insert into Composicao values(66,36,'8 unidades');
insert into Composicao values(67,83,'100 gramas');
insert into Composicao values(67,13,'250 ml');
insert into Composicao values(67,91,'2 unidades');
insert into Composicao values(67,90,'3 colher de sopa');
insert into Composicao values(67,1,'2 colher de sopa');
insert into Composicao values(67,46,'a gosto');
insert into Composicao values(68,18,'1 unidade');
insert into Composicao values(68,94,'2 unidades');
insert into Composicao values(68,117,'uma porção');
insert into Composicao values(68,21,'a gosto');
insert into Composicao values(68,20,'a gosto');
insert into Composicao values(68,90,'3 colheres de sopa');
insert into Composicao values(68,56,'3 colheres');
insert into Composicao values(68,79,'3 unidades');
insert into Composicao values(69,44,'3/4 xícara');
insert into Composicao values(69,67,'1 colher');
insert into Composicao values(69,63,'1 xícara');
insert into Composicao values(69,13,'1 xícara');
insert into Composicao values(69,3,'2 unidades');
insert into Composicao values(69,118,'20 unidades');
insert into Composicao values(69,2,'2 xícaras');
insert into Composicao values(69,7,'3 xícaras');
insert into Composicao values(69,82,'3 unidades');
insert into Composicao values(69,69,'1 unidade');
insert into Composicao values(69,1,'2 colheres de sopa');
insert into Composicao values(69,119,'8 colheres de sopa');
insert into Composicao values(70,3,'4 unidades');
insert into Composicao values(70,63,'500 gramas');
insert into Composicao values(70,1,'2 colheres de sopa');
insert into Composicao values(70,7,'3 xícaras');
insert into Composicao values(70,2,'2 xícaras');
insert into Composicao values(70,67,'2 colheres de chá');
insert into Composicao values(70,13,'1 xícara');
insert into Composicao values(70,69,'1 unidade');
insert into Composicao values(71,3,'1 unidade');
insert into Composicao values(71,7,'4 colheres de sopa');
insert into Composicao values(71,67,'1 colher de chá');
insert into Composicao values(71,2,'1 colher de chá');
insert into Composicao values(71,21,'1 colher de chá');
insert into Composicao values(71,13,'60 ml');
insert into Composicao values(71,120,'1/2 unidade');
insert into Composicao values(71,90,'a gosto');
insert into Composicao values(72,7,'4 xícaras');
insert into Composicao values(72,8,'1 xícara');
insert into Composicao values(72,25,'130 gramas');
insert into Composicao values(72,74,'1 unidade');
insert into Composicao values(72,121,'1/4 xícara');
insert into Composicao values(73,75,'250 gramas');
insert into Composicao values(73,16,'1 unidade');
insert into Composicao values(73,18,'1 unidade');
insert into Composicao values(73,41,'1 unidade');
insert into Composicao values(73,112,'2 unidades');
insert into Composicao values(73,78,'4 unidades');
insert into Composicao values(73,61,'75 gramas');
insert into Composicao values(74,83,'3 copos');
insert into Composicao values(74,26,'2 undiades');
insert into Composicao values(74,17,'1 dente');
insert into Composicao values(74,20,'1 colher de chá');
insert into Composicao values(74,18,'1 colher de chá');
insert into Composicao values(75,1,'1 colher de chá');
insert into Composicao values(75,3,'1 colher de chá');
insert into Composicao values(75,13,'1 colher de chá');

